### ISSUE TITLE
I have a question about the param and FLOPs of AirNet

### ISSUE THREAD

**Issue by progressforever** [Amazingren/AnyIR#2]
Great job! I want to do some research about efficient all-in-one image restoration. However, when I compare the param and FLOPs of SOTA models, I found that the data for AirNet in your article differs from my experimental results. The data I tested for AirNet are 5.77M and 230.66G, but it is 8.93M and 238G in your paper.  I would like to know the reason for this discrepancy so that I can correctly compare these models.

Looking forward to your reply soon. Wishing you all the best.

**Comment by progressforever** [comment]
And looking forward to your early code~. HAHA.
Best wishes~

**Comment by progressforever** [comment]
Sorry, I got the same result.

**Comment by Amazingren** [comment]
> Sorry, I got the same result.

Hi @progressforever ,

Sorry for the late reply. And it's nice you already solved the problem. 

With warm regards,
